export interface SpeedCommand {
  id: number;
  description: string;
  answers: string[];
  category: string;
  difficulty: number;
  hint?: string;
  feedback?: string;
}

export const speedCommands: SpeedCommand[] = [
  { id: 1, description: 'Wyświetl listę plików w bieżącym katalogu z szczegółami', answers: ['ls -l', 'll', 'ls -la', 'ls -al'], category: 'linux', difficulty: 1 },
  { id: 2, description: 'Pokaż bieżącą ścieżkę katalogu', answers: ['pwd'], category: 'linux', difficulty: 1 },
  { id: 3, description: 'Utwórz katalog o nazwie "projekty"', answers: ['mkdir projekty', 'mkdir ./projekty'], category: 'linux', difficulty: 1 },
  { id: 4, description: 'Skopiuj plik /etc/hosts do katalogu domowego', answers: ['cp /etc/hosts ~', 'cp /etc/hosts ~/', 'cp /etc/hosts /home/$USER', 'cp /etc/hosts /home/$(whoami)'], category: 'linux', difficulty: 1 },
  { id: 5, description: 'Zmień nazwę pliku "stary.txt" na "nowy.txt"', answers: ['mv stary.txt nowy.txt'], category: 'linux', difficulty: 1 },
  { id: 6, description: 'Usuń katalog "temp" wraz z całą zawartością', answers: ['rm -rf temp', 'rm -r temp', 'rm -fr temp'], category: 'linux', difficulty: 1 },
  { id: 7, description: 'Stwórz strukturę katalogów: projekty/web, projekty/api, projekty/db', answers: ['mkdir -p projekty/web projekty/api projekty/db', 'mkdir -p projekty/{web,api,db}'], category: 'linux', difficulty: 1 },
  { id: 8, description: 'Wyświetl zawartość pliku /etc/passwd', answers: ['cat /etc/passwd'], category: 'linux', difficulty: 1 },
  { id: 9, description: 'Wyświetl pierwsze 10 linii pliku /var/log/messages', answers: ['head /var/log/messages', 'head -n 10 /var/log/messages'], category: 'linux', difficulty: 1 },
  { id: 10, description: 'Wyświetl ostatnie 20 linii pliku /var/log/syslog', answers: ['tail -n 20 /var/log/syslog', 'tail -20 /var/log/syslog'], category: 'linux', difficulty: 1 },
  { id: 11, description: 'Znajdź wszystkie pliki .conf w katalogu /etc', answers: ['find /etc -name "*.conf"', 'find /etc -type f -name "*.conf"'], category: 'linux', difficulty: 2 },
  { id: 12, description: 'Pokaż użycie dysków w czytelnym formacie', answers: ['df -h', 'df -H'], category: 'system', difficulty: 1 },
  { id: 13, description: 'Pokaż rozmiar katalogu /var/log', answers: ['du -sh /var/log', 'du -sh /var/log/'], category: 'system', difficulty: 1 },
  { id: 14, description: 'Wyświetl wszystkie procesy działające w systemie', answers: ['ps aux', 'ps -ef', 'ps axu'], category: 'system', difficulty: 1 },
  { id: 15, description: 'Wyświetl użycie pamięci RAM', answers: ['free -h', 'free -m', 'free'], category: 'system', difficulty: 1 },
  { id: 16, description: 'Sprawdź status usługi sshd', answers: ['systemctl status sshd', 'systemctl status sshd.service', 'service sshd status'], category: 'system', difficulty: 1 },
  { id: 17, description: 'Uruchom usługę httpd', answers: ['systemctl start httpd', 'systemctl start httpd.service', 'service httpd start'], category: 'system', difficulty: 1 },
  { id: 18, description: 'Dodaj usługę httpd do autostartu', answers: ['systemctl enable httpd', 'systemctl enable httpd.service', 'chkconfig httpd on'], category: 'system', difficulty: 1 },
  { id: 19, description: 'Wyświetl logi usługi sshd z journalctl', answers: ['journalctl -u sshd', 'journalctl -u sshd.service', 'journalctl -u sshd --no-pager'], category: 'system', difficulty: 2 },
  { id: 20, description: 'Wyświetl podgląd na żywo logów systemowych', answers: ['journalctl -f', 'journalctl --follow'], category: 'system', difficulty: 2 },
  { id: 21, description: 'Sprawdź ile miejsca zajmują logi journald', answers: ['journalctl --disk-usage'], category: 'system', difficulty: 3 },
  { id: 22, description: 'Pokaż interfejsy sieciowe i ich adresy IP', answers: ['ip addr', 'ip a', 'ip address', 'ip addr show'], category: 'network', difficulty: 1 },
  { id: 23, description: 'Wyświetl tablicę routingu', answers: ['ip route', 'route -n', 'ip r'], category: 'network', difficulty: 2 },
  { id: 24, description: 'Sprawdź nasłuchujące porty TCP', answers: ['ss -tln', 'ss -tuln', 'netstat -tln', 'netstat -tuln'], category: 'network', difficulty: 2 },
  { id: 25, description: 'Wyślij ping 4 razy do 8.8.8.8', answers: ['ping -c 4 8.8.8.8'], category: 'network', difficulty: 1 },
  { id: 26, description: 'Sprawdź jaki serwer DNS jest używany', answers: ['cat /etc/resolv.conf', 'nmcli dev show | grep DNS', 'resolvectl status'], category: 'network', difficulty: 2 },
  { id: 27, description: 'Pobierz plik z internetu za pomocą curl', answers: ['curl -O https://example.com/file.txt', 'curl -o file.txt https://example.com/file.txt', 'curl https://example.com/file.txt -O'], category: 'network', difficulty: 1 },
  { id: 28, description: 'Dodaj regułę firewalld otwierającą port 8080/tcp', answers: ['firewall-cmd --add-port=8080/tcp', 'firewall-cmd --permanent --add-port=8080/tcp'], category: 'network', difficulty: 2 },
  { id: 29, description: 'Wyświetl nazwę hosta', answers: ['hostname', 'hostnamectl'], category: 'network', difficulty: 1 },
  { id: 30, description: 'Zmień prawa pliku script.sh na wykonywalny dla właściciela', answers: ['chmod u+x script.sh', 'chmod +x script.sh', 'chmod 755 script.sh'], category: 'security', difficulty: 1 },
  { id: 31, description: 'Zmień właściciela pliku na user:group', answers: ['chown user:group plik.txt', 'chown user:group file.txt', 'chown user:group plik'], category: 'security', difficulty: 1 },
  { id: 32, description: 'Dodaj użytkownika "nowy" z katalogiem domowym i shellem bash', answers: ['useradd -m -s /bin/bash nowy', 'useradd -m -s /bin/bash nowy'], category: 'security', difficulty: 2 },
  { id: 33, description: 'Dodaj użytkownika "marek" do grupy "wheel"', answers: ['usermod -aG wheel marek', 'usermod -a -G wheel marek', 'gpasswd -a marek wheel'], category: 'security', difficulty: 2 },
  { id: 34, description: 'Sprawdź status SELinux (tryb działania)', answers: ['getenforce', 'sestatus', 'selinuxenabled'], category: 'security', difficulty: 1 },
  { id: 35, description: 'Tymczasowo wyłącz SELinux (do next reboot)', answers: ['setenforce 0', 'setenforce Permissive'], category: 'security', difficulty: 2 },
  { id: 36, description: 'Wygeneruj klucz SSH ED25519', answers: ['ssh-keygen -t ed25519', 'ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519'], category: 'security', difficulty: 2 },
  { id: 37, description: 'Skopiuj klucz publiczny na serwer', answers: ['ssh-copy-id user@server', 'ssh-copy-id -i ~/.ssh/id_ed25519.pub user@server'], category: 'security', difficulty: 2 },
  { id: 38, description: 'Wyświetl listę aktywnych reguł SELinux dla użytkownika', answers: ['sudo -l', 'sudo -lU $USER'], category: 'security', difficulty: 3 },
  { id: 39, description: 'Wyszukaj linie zawierające "error" w pliku /var/log/messages', answers: ['grep error /var/log/messages', 'grep "error" /var/log/messages'], category: 'shell', difficulty: 1 },
  { id: 40, description: 'Pokaż unikalne linie w pliku (po posortowaniu)', answers: ['sort file.txt | uniq', 'sort file.txt | uniq -u', 'sort -u file.txt'], category: 'shell', difficulty: 2 },
  { id: 41, description: 'Policz liczbę linii w pliku /etc/passwd', answers: ['wc -l /etc/passwd'], category: 'shell', difficulty: 1 },
  { id: 42, description: 'Wyświetl 1. kolumnę z pliku /etc/passwd (oddzielonego :)', answers: ['cut -d: -f1 /etc/passwd', 'awk -F: \'{print $1}\' /etc/passwd'], category: 'shell', difficulty: 2 },
  { id: 43, description: 'Znajdź plik .bashrc za pomocą bazy danych', answers: ['locate .bashrc'], category: 'linux', difficulty: 1 },
  { id: 44, description: 'Pokaż typ pliku /bin/bash', answers: ['file /bin/bash'], category: 'linux', difficulty: 1 },
  { id: 45, description: 'Stwórz dowiązanie symboliczne /link do /target', answers: ['ln -s /target /link', 'ln -s /target link'], category: 'linux', difficulty: 2 },
  { id: 46, description: 'Wyświetl szczegółowe informacje o pliku /etc/passwd', answers: ['stat /etc/passwd'], category: 'linux', difficulty: 1 },
  { id: 47, description: 'Wyświetl drzewo katalogów z ograniczeniem do 2 poziomów', answers: ['tree -L 2', 'tree -L 2 /'], category: 'linux', difficulty: 1 },
  { id: 48, description: 'Zainstaluj pakiet nginx (RHEL/DNF)', answers: ['dnf install -y nginx', 'dnf install nginx', 'yum install -y nginx'], category: 'system', difficulty: 2 },
  { id: 49, description: 'Zaktualizuj wszystkie pakiety w systemie', answers: ['dnf update -y', 'dnf upgrade -y', 'yum update -y'], category: 'system', difficulty: 1 },
  { id: 50, description: 'Pokaż listę dostępnych modułów DNF', answers: ['dnf module list', 'dnf module list --enabled'], category: 'system', difficulty: 3 },
  { id: 51, description: 'Wyświetl partycje i systemy plików', answers: ['lsblk -f', 'lsblk', 'blkid'], category: 'system', difficulty: 1 },
  { id: 52, description: 'Pokaż woluminy logiczne LVM', answers: ['lvs', 'lvdisplay', 'lvscan'], category: 'system', difficulty: 2 },
  { id: 53, description: 'Stwórz snapshot LVM o nazwie snap o rozmiarze 1G', answers: ['lvcreate -s -n snap -L 1G /dev/vg_data/lv_data', 'lvcreate --snapshot -n snap -L 1G /dev/vg_data/lv_data'], category: 'system', difficulty: 3 },
  { id: 54, description: 'Zmień profil tuned na "virtual-host"', answers: ['tuned-adm profile virtual-host', 'tuned-adm profile virtual-host'], category: 'system', difficulty: 3 },
  { id: 55, description: 'Dodaj regułę iptables blokującą port 22', answers: ['iptables -A INPUT -p tcp --dport 22 -j DROP', 'iptables -A INPUT -p tcp --dport 22 -j REJECT'], category: 'network', difficulty: 3 },
  { id: 56, description: 'Wyświetl wszystkie obrazy w Podman/Docker', answers: ['podman images', 'docker images', 'podman image ls'], category: 'devops', difficulty: 1 },
  { id: 57, description: 'Uruchom kontener Nginx w tle na porcie 80', answers: ['podman run -d -p 80:80 nginx', 'docker run -d -p 80:80 nginx', 'podman run -d --name web -p 80:80 nginx'], category: 'devops', difficulty: 2 },
  { id: 58, description: 'Wyświetl działające kontenery', answers: ['podman ps', 'docker ps', 'podman container ls'], category: 'devops', difficulty: 1 },
  { id: 59, description: 'Wygeneruj plik Containerfile/Dockerfile z obrazem Fedory', answers: ['echo "FROM fedora" > Containerfile', 'echo "FROM fedora" > Dockerfile'], category: 'devops', difficulty: 2 },
  { id: 60, description: 'Sprawdź wersję systemu RHEL', answers: ['cat /etc/redhat-release', 'cat /etc/os-release', 'hostnamectl | grep Operating', 'rpm -q redhat-release'], category: 'system', difficulty: 1 },
  { id: 61, description: 'Wyświetl bilet Kerberos ( ticket-granting ticket)', answers: ['klist', 'kinit', 'klist -A'], category: 'security', difficulty: 3 },
  { id: 62, description: 'Pokaż załadowane moduły jądra', answers: ['lsmod'], category: 'system', difficulty: 1 },
  { id: 63, description: 'Zablokuj konto użytkownika "marek"', answers: ['usermod -L marek', 'passwd -l marek', 'usermod --lock marek'], category: 'security', difficulty: 2 },
  { id: 64, description: 'Ustaw dzienny cel nauki w RootForge na 45 minut', answers: ['rootforge-set-goal 45', 'nie dotyczy – użyj GUI'], category: 'linux', difficulty: 1, hint: 'To się robi przez GUI w ustawieniach' },
  { id: 65, description: 'Wyświetl informacje o CPU', answers: ['lscpu', 'cat /proc/cpuinfo | grep "model name"', 'cat /proc/cpuinfo'], category: 'system', difficulty: 1 },
  { id: 66, description: 'Sprawdź czas działania systemu', answers: ['uptime'], category: 'system', difficulty: 1 },
  { id: 67, description: 'Wyświetl listę zadań cron dla bieżącego użytkownika', answers: ['crontab -l'], category: 'system', difficulty: 2 },
  { id: 68, description: 'Edytuj plik sudoers bezpiecznie', answers: ['visudo'], category: 'security', difficulty: 1 },
  { id: 69, description: 'Wyświetl szczegółowe informacje o PCI w systemie', answers: ['lspci', 'lspci -v', 'lspci -vvv'], category: 'system', difficulty: 2 },
  { id: 70, description: 'Zrestartuj usługę NetworkManager', answers: ['systemctl restart NetworkManager', 'systemctl restart NetworkManager.service', 'service NetworkManager restart'], category: 'network', difficulty: 1 },
  { id: 71, description: 'Zapisz czas systemowy do zegara sprzętowego', answers: ['hwclock --systohc'], category: 'system', difficulty: 2 },
  { id: 72, description: 'Pokaż szczegóły synchronizacji NTP (chronyd)', answers: ['chronyc tracking', 'chronyc -n tracking'], category: 'system', difficulty: 2 },
  { id: 73, description: 'Pokaż serwery NTP używane przez chronyd', answers: ['chronyc sources -v', 'chronyc sources'], category: 'system', difficulty: 2 },
  { id: 74, description: 'Wyświetl UUID wszystkich systemów plików', answers: ['blkid', 'lsblk -f'], category: 'system', difficulty: 1 },
  { id: 75, description: 'Pokaż drzewo zamontowanych systemów plików', answers: ['findmnt', 'findmnt -l'], category: 'system', difficulty: 1 },
  { id: 76, description: 'Zamontuj wszystkie systemy z /etc/fstab', answers: ['mount -a'], category: 'system', difficulty: 2 },
  { id: 77, description: 'Sprawdź poprawność konfiguracji Samba', answers: ['testparm'], category: 'network', difficulty: 2 },
  { id: 78, description: 'Wyświetl status udziałów Samba', answers: ['smbstatus'], category: 'network', difficulty: 2 },
  { id: 79, description: 'Wyświetl reguły auditd', answers: ['auditctl -l'], category: 'security', difficulty: 3 },
  { id: 80, description: 'Wyszukaj zdarzenia auditd z kluczem "passwd_changes"', answers: ['ausearch -k passwd_changes', 'ausearch -k passwd_changes -i'], category: 'security', difficulty: 3 },
  { id: 81, description: 'Wygeneruj raport podsumowujący auditd', answers: ['aureport --summary'], category: 'security', difficulty: 3 },
  { id: 82, description: 'Włącz lingering dla bieżącego użytkownika (kontenery po logout)', answers: ['loginctl enable-linger'], category: 'devops', difficulty: 3 },
  { id: 83, description: 'Wygeneruj plik systemd dla kontenera Podman', answers: ['podman generate systemd --name web --files', 'podman generate systemd --name web'], category: 'devops', difficulty: 3 },
  { id: 84, description: 'Pokaż tryb SELinux (Enforcing/Permissive/Disabled)', answers: ['getenforce', 'sestatus | head -1'], category: 'security', difficulty: 1 },
  { id: 85, description: 'Trwale zmień domyślny kontekst SELinux dla katalogu', answers: ['semanage fcontext -a -t httpd_sys_content_t /dir', 'semanage fcontext -a -t httpd_sys_content_t /katalog'], category: 'security', difficulty: 3 },
  { id: 86, description: 'Zastosuj domyślne konteksty SELinux rekurencyjnie', answers: ['restorecon -R /dir', 'restorecon -Rv /katalog'], category: 'security', difficulty: 2 },
  { id: 87, description: 'Zainstaluj system przez plik kickstart', answers: ['linux ks=http://server/ks.cfg', 'inst.ks=http://server/ks.cfg'], category: 'system', difficulty: 3, hint: 'Dodaj parametr do linii bootloadera podczas instalacji' },
  { id: 88, description: 'Dodaj użytkownika Samba i ustaw hasło', answers: ['smbpasswd -a jan', 'smbpasswd -a username'], category: 'network', difficulty: 2 },
  { id: 89, description: 'Zarejestruj system RHEL w Red Hat Subscription Manager', answers: ['subscription-manager register --username user --password pass'], category: 'system', difficulty: 2 },
  { id: 90, description: 'Sprawdź konwersję daty na timestamp Unix', answers: ['date --date "2025-03-24 12:00:00" +%s', 'date -d "2025-03-24 12:00:00" +%s'], category: 'linux', difficulty: 2 },

  { id: 91, description: 'Zbuduj obraz Docker z Dockerfile', answers: ['docker build -t myapp .', 'docker build -t myapp:latest .'], category: 'devops', difficulty: 2 },
  { id: 92, description: 'Uruchom kontener Docker w tle', answers: ['docker run -d nginx', 'docker run -d --name web nginx'], category: 'devops', difficulty: 2 },
  { id: 93, description: 'Wyswietl dzialajace kontenery', answers: ['docker ps', 'docker container ls'], category: 'devops', difficulty: 1 },
  { id: 94, description: 'Zatrzymaj kontener Docker', answers: ['docker stop $(docker ps -ql)', 'docker stop kontener'], category: 'devops', difficulty: 1 },
  { id: 95, description: 'Wyswietl obrazy Docker', answers: ['docker images', 'docker image ls'], category: 'devops', difficulty: 1 },
  { id: 96, description: 'Wykonaj komende w dzialajacym kontenerze', answers: ['docker exec -it kontener bash', 'docker exec -it kontener sh'], category: 'devops', difficulty: 2 },
  { id: 97, description: 'Wyswietl logi kontenera', answers: ['docker logs kontener', 'docker logs -f kontener'], category: 'devops', difficulty: 1 },
  { id: 98, description: 'Wyswietl wszystkie pody K8s', answers: ['kubectl get pods', 'kubectl get pods -A', 'kubectl get pods --all-namespaces'], category: 'devops', difficulty: 2 },
  { id: 99, description: 'Wyswietl deploymenty K8s', answers: ['kubectl get deployments', 'kubectl get deploy'], category: 'devops', difficulty: 2 },
  { id: 100, description: 'Skaluj deployment K8s do 5 replik', answers: ['kubectl scale deployment myapp --replicas=5'], category: 'devops', difficulty: 3 },
  { id: 101, description: 'Stworz namespace K8s', answers: ['kubectl create namespace myns'], category: 'devops', difficulty: 2 },
  { id: 102, description: 'Wyswietl serwisy K8s', answers: ['kubectl get svc', 'kubectl get services'], category: 'devops', difficulty: 2 },
  { id: 103, description: 'Sprawdz status Git', answers: ['git status'], category: 'devops', difficulty: 1 },
  { id: 104, description: 'Stworz nowa galaz Git', answers: ['git checkout -b nowa-funkcja', 'git branch nowa-funkcja'], category: 'devops', difficulty: 1 },
  { id: 105, description: 'Polacz galaz Git przez merge', answers: ['git merge nowa-funkcja'], category: 'devops', difficulty: 2 },
  { id: 106, description: 'Inicjalizuj Terraform', answers: ['terraform init'], category: 'devops', difficulty: 2 },
  { id: 107, description: 'Zaplanuj zmiany Terraform', answers: ['terraform plan', 'terraform plan -out plan.tfplan'], category: 'devops', difficulty: 2 },
  { id: 108, description: 'Aplikuj zmiany Terraform', answers: ['terraform apply', 'terraform apply --auto-approve'], category: 'devops', difficulty: 2 },
  { id: 109, description: 'Listuj bucket S3', answers: ['aws s3 ls', 'aws s3 ls s3://bucket'], category: 'devops', difficulty: 2 },
  { id: 110, description: 'Opisz instancje EC2', answers: ['aws ec2 describe-instances'], category: 'devops', difficulty: 2 },
];